chore: Update release workflow to push the latest gem version and bump view_component_toolkit version to 0.1.17

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -37,16 +37,27 @@ jobs:
 
     - name: Push to GitHub Packages
       run: |
-        gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB }}
-
+        GEM_NAME=$(ls *.gem | head -n 1)
+        OWNER="${GITHUB_REPOSITORY_OWNER}"
+        GITHUB_TOKEN="${{ secrets.GITHUB }}"
+        
+        RESPONSE=$(curl -s -u "${OWNER}:${GITHUB_TOKEN}" -H "Content-Type: application/octet-stream" --data-binary @"${GEM_NAME}" "https://rubygems.pkg.github.com/${OWNER}/api/v1/gems")
+        
+        if echo "$RESPONSE" | grep -q '"success":true'; then
+          echo "Successfully pushed ${GEM_NAME} to GitHub Packages"
+        else
+          echo "Failed to push ${GEM_NAME} to GitHub Packages"
+          echo "Response: $RESPONSE"
+          exit 1
+        fi
+ 
     - name: Push to RubyGems
       run: |
         mkdir -p $HOME/.gem
         touch $HOME/.gem/credentials
         chmod 0600 $HOME/.gem/credentials
         printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
-        gem push *.gem
+        GEM_NAME=$(ls *.gem | head -n 1)
+        gem push $GEM_NAME
       env:
         GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
